[package]
name = "rusty-agents"
version = "0.1.0"
authors = ["Jonathan Harper <jharper+moar@unity3d.com>"]
edition = "2018"

[dependencies]
grpcio = "0.6"
tch = "0.2"
cpython = "0.2.0"
protobuf = "2.0"
futures = "0.3"
log = "0.4.11"
thiserror = "1.0"
rand = "0.7.3"