// This file is generated by rust-protobuf 2.17.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `mlagents_envs/communicator_objects/agent_action.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_17_0;

#[derive(PartialEq,Clone,Default)]
pub struct AgentActionProto {
    // message fields
    pub vector_actions: ::std::vec::Vec<f32>,
    pub value: f32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AgentActionProto {
    fn default() -> &'a AgentActionProto {
        <AgentActionProto as ::protobuf::Message>::default_instance()
    }
}

impl AgentActionProto {
    pub fn new() -> AgentActionProto {
        ::std::default::Default::default()
    }

    // repeated float vector_actions = 1;


    pub fn get_vector_actions(&self) -> &[f32] {
        &self.vector_actions
    }
    pub fn clear_vector_actions(&mut self) {
        self.vector_actions.clear();
    }

    // Param is passed by value, moved
    pub fn set_vector_actions(&mut self, v: ::std::vec::Vec<f32>) {
        self.vector_actions = v;
    }

    // Mutable pointer to the field.
    pub fn mut_vector_actions(&mut self) -> &mut ::std::vec::Vec<f32> {
        &mut self.vector_actions
    }

    // Take field
    pub fn take_vector_actions(&mut self) -> ::std::vec::Vec<f32> {
        ::std::mem::replace(&mut self.vector_actions, ::std::vec::Vec::new())
    }

    // float value = 4;


    pub fn get_value(&self) -> f32 {
        self.value
    }
    pub fn clear_value(&mut self) {
        self.value = 0.;
    }

    // Param is passed by value, moved
    pub fn set_value(&mut self, v: f32) {
        self.value = v;
    }
}

impl ::protobuf::Message for AgentActionProto {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_float_into(wire_type, is, &mut self.vector_actions)?;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed32 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_float()?;
                    self.value = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += 5 * self.vector_actions.len() as u32;
        if self.value != 0. {
            my_size += 5;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.vector_actions {
            os.write_float(1, *v)?;
        };
        if self.value != 0. {
            os.write_float(4, self.value)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AgentActionProto {
        AgentActionProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                "vector_actions",
                |m: &AgentActionProto| { &m.vector_actions },
                |m: &mut AgentActionProto| { &mut m.vector_actions },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeFloat>(
                "value",
                |m: &AgentActionProto| { &m.value },
                |m: &mut AgentActionProto| { &mut m.value },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<AgentActionProto>(
                "AgentActionProto",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static AgentActionProto {
        static instance: ::protobuf::rt::LazyV2<AgentActionProto> = ::protobuf::rt::LazyV2::INIT;
        instance.get(AgentActionProto::new)
    }
}

impl ::protobuf::Clear for AgentActionProto {
    fn clear(&mut self) {
        self.vector_actions.clear();
        self.value = 0.;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AgentActionProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AgentActionProto {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n5mlagents_envs/communicator_objects/agent_action.proto\x12\x14communic\
    ator_objects\"a\n\x10AgentActionProto\x12%\n\x0evector_actions\x18\x01\
    \x20\x03(\x02R\rvectorActions\x12\x14\n\x05value\x18\x04\x20\x01(\x02R\
    \x05valueJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x05\x10\x06\
    B%\xaa\x02\"Unity.MLAgents.CommunicatorObjectsJ\xe8\x03\n\x06\x12\x04\0\
    \0\x0b\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x08\x12\x03\x02\0\
    ?\n\t\n\x02\x08%\x12\x03\x02\0?\n\x08\n\x01\x02\x12\x03\x03\0\x1d\n\n\n\
    \x02\x04\0\x12\x04\x05\0\x0b\x01\n\n\n\x03\x04\0\x01\x12\x03\x05\x08\x18\
    \n\x0b\n\x04\x04\0\x02\0\x12\x03\x06\x04&\n\x0c\n\x05\x04\0\x02\0\x04\
    \x12\x03\x06\x04\x0c\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x06\r\x12\n\x0c\
    \n\x05\x04\0\x02\0\x01\x12\x03\x06\x13!\n\x0c\n\x05\x04\0\x02\0\x03\x12\
    \x03\x06$%\n1\n\x03\x04\0\t\x12\x03\x07\x04\x0f\"%\x20deprecated\x20stri\
    ng\x20text_actions\x20=\x202;\n\n\x0b\n\x04\x04\0\t\0\x12\x03\x07\r\x0e\
    \n\x0c\n\x05\x04\0\t\0\x01\x12\x03\x07\r\x0e\n\x0c\n\x05\x04\0\t\0\x02\
    \x12\x03\x07\r\x0e\n4\n\x03\x04\0\t\x12\x03\x08\x04\x0f\"(deprecated\x20\
    repeated\x20float\x20memories\x20=\x203;\n\n\x0b\n\x04\x04\0\t\x01\x12\
    \x03\x08\r\x0e\n\x0c\n\x05\x04\0\t\x01\x01\x12\x03\x08\r\x0e\n\x0c\n\x05\
    \x04\0\t\x01\x02\x12\x03\x08\r\x0e\n\x0b\n\x04\x04\0\x02\x01\x12\x03\t\
    \x04\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\t\x04\t\n\x0c\n\x05\x04\0\
    \x02\x01\x01\x12\x03\t\n\x0f\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\t\x12\
    \x13\n=\n\x03\x04\0\t\x12\x03\n\x04\x0f\"1\x20deprecated\x20CustomAction\
    Proto\x20custom_action\x20=\x205;\n\n\x0b\n\x04\x04\0\t\x02\x12\x03\n\r\
    \x0e\n\x0c\n\x05\x04\0\t\x02\x01\x12\x03\n\r\x0e\n\x0c\n\x05\x04\0\t\x02\
    \x02\x12\x03\n\r\x0eb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
