// This file is generated by rust-protobuf 2.17.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `mlagents_envs/communicator_objects/agent_info_action_pair.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_17_0;

#[derive(PartialEq,Clone,Default)]
pub struct AgentInfoActionPairProto {
    // message fields
    pub agent_info: ::protobuf::SingularPtrField<super::agent_info::AgentInfoProto>,
    pub action_info: ::protobuf::SingularPtrField<super::agent_action::AgentActionProto>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a AgentInfoActionPairProto {
    fn default() -> &'a AgentInfoActionPairProto {
        <AgentInfoActionPairProto as ::protobuf::Message>::default_instance()
    }
}

impl AgentInfoActionPairProto {
    pub fn new() -> AgentInfoActionPairProto {
        ::std::default::Default::default()
    }

    // .communicator_objects.AgentInfoProto agent_info = 1;


    pub fn get_agent_info(&self) -> &super::agent_info::AgentInfoProto {
        self.agent_info.as_ref().unwrap_or_else(|| <super::agent_info::AgentInfoProto as ::protobuf::Message>::default_instance())
    }
    pub fn clear_agent_info(&mut self) {
        self.agent_info.clear();
    }

    pub fn has_agent_info(&self) -> bool {
        self.agent_info.is_some()
    }

    // Param is passed by value, moved
    pub fn set_agent_info(&mut self, v: super::agent_info::AgentInfoProto) {
        self.agent_info = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_agent_info(&mut self) -> &mut super::agent_info::AgentInfoProto {
        if self.agent_info.is_none() {
            self.agent_info.set_default();
        }
        self.agent_info.as_mut().unwrap()
    }

    // Take field
    pub fn take_agent_info(&mut self) -> super::agent_info::AgentInfoProto {
        self.agent_info.take().unwrap_or_else(|| super::agent_info::AgentInfoProto::new())
    }

    // .communicator_objects.AgentActionProto action_info = 2;


    pub fn get_action_info(&self) -> &super::agent_action::AgentActionProto {
        self.action_info.as_ref().unwrap_or_else(|| <super::agent_action::AgentActionProto as ::protobuf::Message>::default_instance())
    }
    pub fn clear_action_info(&mut self) {
        self.action_info.clear();
    }

    pub fn has_action_info(&self) -> bool {
        self.action_info.is_some()
    }

    // Param is passed by value, moved
    pub fn set_action_info(&mut self, v: super::agent_action::AgentActionProto) {
        self.action_info = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_action_info(&mut self) -> &mut super::agent_action::AgentActionProto {
        if self.action_info.is_none() {
            self.action_info.set_default();
        }
        self.action_info.as_mut().unwrap()
    }

    // Take field
    pub fn take_action_info(&mut self) -> super::agent_action::AgentActionProto {
        self.action_info.take().unwrap_or_else(|| super::agent_action::AgentActionProto::new())
    }
}

impl ::protobuf::Message for AgentInfoActionPairProto {
    fn is_initialized(&self) -> bool {
        for v in &self.agent_info {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.action_info {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.agent_info)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.action_info)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.agent_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.action_info.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.agent_info.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.action_info.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> AgentInfoActionPairProto {
        AgentInfoActionPairProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::agent_info::AgentInfoProto>>(
                "agent_info",
                |m: &AgentInfoActionPairProto| { &m.agent_info },
                |m: &mut AgentInfoActionPairProto| { &mut m.agent_info },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::agent_action::AgentActionProto>>(
                "action_info",
                |m: &AgentInfoActionPairProto| { &m.action_info },
                |m: &mut AgentInfoActionPairProto| { &mut m.action_info },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<AgentInfoActionPairProto>(
                "AgentInfoActionPairProto",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static AgentInfoActionPairProto {
        static instance: ::protobuf::rt::LazyV2<AgentInfoActionPairProto> = ::protobuf::rt::LazyV2::INIT;
        instance.get(AgentInfoActionPairProto::new)
    }
}

impl ::protobuf::Clear for AgentInfoActionPairProto {
    fn clear(&mut self) {
        self.agent_info.clear();
        self.action_info.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for AgentInfoActionPairProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for AgentInfoActionPairProto {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n?mlagents_envs/communicator_objects/agent_info_action_pair.proto\x12\
    \x14communicator_objects\x1a3mlagents_envs/communicator_objects/agent_in\
    fo.proto\x1a5mlagents_envs/communicator_objects/agent_action.proto\"\xa8\
    \x01\n\x18AgentInfoActionPairProto\x12C\n\nagent_info\x18\x01\x20\x01(\
    \x0b2$.communicator_objects.AgentInfoProtoR\tagentInfo\x12G\n\x0baction_\
    info\x18\x02\x20\x01(\x0b2&.communicator_objects.AgentActionProtoR\nacti\
    onInfoB%\xaa\x02\"Unity.MLAgents.CommunicatorObjectsJ\xcd\x01\n\x06\x12\
    \x04\0\0\x0b\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\t\n\x02\x03\0\x12\x03\
    \x02\0=\n\t\n\x02\x03\x01\x12\x03\x03\0?\n\x08\n\x01\x08\x12\x03\x05\0?\
    \n\t\n\x02\x08%\x12\x03\x05\0?\n\x08\n\x01\x02\x12\x03\x06\0\x1d\n\n\n\
    \x02\x04\0\x12\x04\x08\0\x0b\x01\n\n\n\x03\x04\0\x01\x12\x03\x08\x08\x20\
    \n\x0b\n\x04\x04\0\x02\0\x12\x03\t\x04\"\n\x0c\n\x05\x04\0\x02\0\x06\x12\
    \x03\t\x04\x12\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\t\x13\x1d\n\x0c\n\x05\
    \x04\0\x02\0\x03\x12\x03\t\x20!\n\x0b\n\x04\x04\0\x02\x01\x12\x03\n\x04%\
    \n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03\n\x04\x14\n\x0c\n\x05\x04\0\x02\
    \x01\x01\x12\x03\n\x15\x20\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\n#$b\
    \x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
