// This file is generated by rust-protobuf 2.17.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `mlagents_envs/communicator_objects/capabilities.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_17_0;

#[derive(PartialEq,Clone,Default)]
pub struct UnityRLCapabilitiesProto {
    // message fields
    pub baseRLCapabilities: bool,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UnityRLCapabilitiesProto {
    fn default() -> &'a UnityRLCapabilitiesProto {
        <UnityRLCapabilitiesProto as ::protobuf::Message>::default_instance()
    }
}

impl UnityRLCapabilitiesProto {
    pub fn new() -> UnityRLCapabilitiesProto {
        ::std::default::Default::default()
    }

    // bool baseRLCapabilities = 1;


    pub fn get_baseRLCapabilities(&self) -> bool {
        self.baseRLCapabilities
    }
    pub fn clear_baseRLCapabilities(&mut self) {
        self.baseRLCapabilities = false;
    }

    // Param is passed by value, moved
    pub fn set_baseRLCapabilities(&mut self, v: bool) {
        self.baseRLCapabilities = v;
    }
}

impl ::protobuf::Message for UnityRLCapabilitiesProto {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_bool()?;
                    self.baseRLCapabilities = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.baseRLCapabilities != false {
            my_size += 2;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.baseRLCapabilities != false {
            os.write_bool(1, self.baseRLCapabilities)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UnityRLCapabilitiesProto {
        UnityRLCapabilitiesProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBool>(
                "baseRLCapabilities",
                |m: &UnityRLCapabilitiesProto| { &m.baseRLCapabilities },
                |m: &mut UnityRLCapabilitiesProto| { &mut m.baseRLCapabilities },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<UnityRLCapabilitiesProto>(
                "UnityRLCapabilitiesProto",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static UnityRLCapabilitiesProto {
        static instance: ::protobuf::rt::LazyV2<UnityRLCapabilitiesProto> = ::protobuf::rt::LazyV2::INIT;
        instance.get(UnityRLCapabilitiesProto::new)
    }
}

impl ::protobuf::Clear for UnityRLCapabilitiesProto {
    fn clear(&mut self) {
        self.baseRLCapabilities = false;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UnityRLCapabilitiesProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UnityRLCapabilitiesProto {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n5mlagents_envs/communicator_objects/capabilities.proto\x12\x14communic\
    ator_objects\"J\n\x18UnityRLCapabilitiesProto\x12.\n\x12baseRLCapabiliti\
    es\x18\x01\x20\x01(\x08R\x12baseRLCapabilitiesB%\xaa\x02\"Unity.MLAgents\
    .CommunicatorObjectsJ\x8d\x02\n\x06\x12\x04\0\0\x0c\x01\n\x08\n\x01\x0c\
    \x12\x03\0\0\x12\n\x08\n\x01\x08\x12\x03\x02\0?\n\t\n\x02\x08%\x12\x03\
    \x02\0?\n\x08\n\x01\x02\x12\x03\x03\0\x1d\nt\n\x02\x04\0\x12\x04\t\0\x0c\
    \x01\x1ah\n\x20A\x20Capabilities\x20message\x20that\x20will\x20communica\
    te\x20both\x20C#\x20and\x20Python\n\x20what\x20features\x20are\x20availa\
    ble\x20to\x20both.\n\n\n\n\x03\x04\0\x01\x12\x03\t\x08\x20\n.\n\x04\x04\
    \0\x02\0\x12\x03\x0b\x04\x20\x1a!\x20These\x20are\x20the\x201.0\x20capab\
    ilities.\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x0b\x04\x08\n\x0c\n\x05\
    \x04\0\x02\0\x01\x12\x03\x0b\t\x1b\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\
    \x0b\x1e\x1fb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
