// This file is generated by rust-protobuf 2.17.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `mlagents_envs/communicator_objects/space_type.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_17_0;

#[derive(Clone,PartialEq,Eq,Debug,Hash)]
pub enum SpaceTypeProto {
    discrete = 0,
    continuous = 1,
}

impl ::protobuf::ProtobufEnum for SpaceTypeProto {
    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<SpaceTypeProto> {
        match value {
            0 => ::std::option::Option::Some(SpaceTypeProto::discrete),
            1 => ::std::option::Option::Some(SpaceTypeProto::continuous),
            _ => ::std::option::Option::None
        }
    }

    fn values() -> &'static [Self] {
        static values: &'static [SpaceTypeProto] = &[
            SpaceTypeProto::discrete,
            SpaceTypeProto::continuous,
        ];
        values
    }

    fn enum_descriptor_static() -> &'static ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            ::protobuf::reflect::EnumDescriptor::new_pb_name::<SpaceTypeProto>("SpaceTypeProto", file_descriptor_proto())
        })
    }
}

impl ::std::marker::Copy for SpaceTypeProto {
}

impl ::std::default::Default for SpaceTypeProto {
    fn default() -> Self {
        SpaceTypeProto::discrete
    }
}

impl ::protobuf::reflect::ProtobufValue for SpaceTypeProto {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Enum(::protobuf::ProtobufEnum::descriptor(self))
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n3mlagents_envs/communicator_objects/space_type.proto\x12\x14communicat\
    or_objects*.\n\x0eSpaceTypeProto\x12\x0c\n\x08discrete\x10\0\x12\x0e\n\n\
    continuous\x10\x01B%\xaa\x02\"Unity.MLAgents.CommunicatorObjectsJ\x9b\
    \x01\n\x06\x12\x04\0\0\x08\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\
    \x01\x08\x12\x03\x02\0?\n\t\n\x02\x08%\x12\x03\x02\0?\n\x08\n\x01\x02\
    \x12\x03\x03\0\x1d\n\n\n\x02\x05\0\x12\x04\x05\0\x08\x01\n\n\n\x03\x05\0\
    \x01\x12\x03\x05\x05\x13\n\x0b\n\x04\x05\0\x02\0\x12\x03\x06\x04\x11\n\
    \x0c\n\x05\x05\0\x02\0\x01\x12\x03\x06\x04\x0c\n\x0c\n\x05\x05\0\x02\0\
    \x02\x12\x03\x06\x0f\x10\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x07\x04\x13\n\
    \x0c\n\x05\x05\0\x02\x01\x01\x12\x03\x07\x04\x0e\n\x0c\n\x05\x05\0\x02\
    \x01\x02\x12\x03\x07\x11\x12b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
